### PR TITLE
conditional steps addition examples

### PR DESCRIPTION
**Pull request by miltolstoy**
Temporary PR for conditional steps addition implementation discussion.

- test_conditional_steps.py - usage examples; will be removed or refactored to be real tests
- configuration_support.py - draft implementation
- artifact_collector.py - draft unrelated bug fix, will be prepared in a separate PR

Check examples output by:
```
pytest -s tests/test_conditional_steps.py -k "test_example"
```

### CODE REVIEW

**Comment by miltolstoy** [comment]
```
========================================================================================================================================================================================================
Conditional + regular step
========================================================================================================================================================================================================
==> Universum 0.19.17 started execution
1. Preparing repository
 |   ==> Adding file /tmp/pytest-of-alelyak/pytest-25/test_example_10/artifacts/REPOSITORY_STATE.txt to artifacts...
 |   1.1. Copying sources to working directory
 |      |   ==> Moving sources to '/tmp/pytest-of-alelyak/pytest-25/test_example_10/project_root'...
 |      └ [Success]
 |   
 |   1.2. Registering file diff for API
 |      └ [Success]
 |   
 └ [Success]

2. Processing project configs
 |   ==> Adding file /tmp/pytest-of-alelyak/pytest-25/test_example_10/artifacts/CONFIGS_DUMP.txt to artifacts...
 └ [Success]

3. Preprocessing artifact lists
 └ [Success]

4. Reporting build start
 |   ==> Nowhere to report. Skipping...
 └ [Success]

5. Executing build steps
 |   5.1.  [ 1/2 ] conditional regular
 |      |   ==> No 'command' found. Nothing to execute
 |      └ [Success]
 |   
 |   5.2.  [ 2/2 ] true_branch
 |      |   ==> No 'command' found. Nothing to execute
 |      └ [Success]
 |   
 └ [Success]

6. Reporting build result
 |   ==> Here is the summarized build result:
 |   ==> 5. Executing build steps
 |   ==>   5.1.  [ 1/2 ] conditional regular - Success
 |   ==>   5.2.  [ 2/2 ] true_branch - Success
 |   ==> Nowhere to report. Skipping...
 └ [Success]

7. Finalizing
 |   7.1. Cleaning copied sources
 |      └ [Success]
 |   
 └ [Success]

==> Universum 0.19.17 finished execution
```

**Comment by miltolstoy** [comment]
```
========================================================================================================================================================================================================
Conditional + conditional step
========================================================================================================================================================================================================
==> Universum 0.19.17 started execution
1. Preparing repository
 |   ==> Adding file /tmp/pytest-of-alelyak/pytest-25/test_example_20/artifacts/REPOSITORY_STATE.txt to artifacts...
 |   1.1. Copying sources to working directory
 |      |   ==> Moving sources to '/tmp/pytest-of-alelyak/pytest-25/test_example_20/project_root'...
 |      └ [Success]
 |   
 |   1.2. Registering file diff for API
 |      └ [Success]
 |   
 └ [Success]

2. Processing project configs
 |   ==> Adding file /tmp/pytest-of-alelyak/pytest-25/test_example_20/artifacts/CONFIGS_DUMP.txt to artifacts...
 └ [Success]

3. Preprocessing artifact lists
 └ [Success]

4. Reporting build start
 |   ==> Nowhere to report. Skipping...
 └ [Success]

5. Executing build steps
 |   5.1.  [ 1/2 ] conditional1 conditional2
 |      |   ==> No 'command' found. Nothing to execute
 |      └ [Success]
 |   
 |   5.2.  [ 2/2 ] true_branch1
 |      |   ==> No 'command' found. Nothing to execute
 |      └ [Success]
 |   
 |   5.3.  [ 3/2 ] true_branch2
 |      |   ==> No 'command' found. Nothing to execute
 |      └ [Success]
 |   
 └ [Success]

6. Reporting build result
 |   ==> Here is the summarized build result:
 |   ==> 5. Executing build steps
 |   ==>   5.1.  [ 1/2 ] conditional1 conditional2 - Success
 |   ==>   5.2.  [ 2/2 ] true_branch1 - Success
 |   ==>   5.3.  [ 3/2 ] true_branch2 - Success
 |   ==> Nowhere to report. Skipping...
 └ [Success]

7. Finalizing
 |   7.1. Cleaning copied sources
 |      └ [Success]
 |   
 └ [Success]

==> Universum 0.19.17 finished execution
```

**Comment by miltolstoy** [comment]
```
========================================================================================================================================================================================================
Conditional without branch + conditional step with branch
========================================================================================================================================================================================================
==> Universum 0.19.17 started execution
1. Preparing repository
 |   ==> Adding file /tmp/pytest-of-alelyak/pytest-25/test_example_30/artifacts/REPOSITORY_STATE.txt to artifacts...
 |   1.1. Copying sources to working directory
 |      |   ==> Moving sources to '/tmp/pytest-of-alelyak/pytest-25/test_example_30/project_root'...
 |      └ [Success]
 |   
 |   1.2. Registering file diff for API
 |      └ [Success]
 |   
 └ [Success]

2. Processing project configs
 |   ==> Adding file /tmp/pytest-of-alelyak/pytest-25/test_example_30/artifacts/CONFIGS_DUMP.txt to artifacts...
 └ [Success]

3. Preprocessing artifact lists
 └ [Success]

4. Reporting build start
 |   ==> Nowhere to report. Skipping...
 └ [Success]

5. Executing build steps
 |   5.1.  [ 1/2 ] conditional1 conditional2
 |      |   ==> No 'command' found. Nothing to execute
 |      └ [Success]
 |   
 |   5.2.  [ 2/2 ] true_branch
 |      |   ==> No 'command' found. Nothing to execute
 |      └ [Success]
 |   
 └ [Success]

6. Reporting build result
 |   ==> Here is the summarized build result:
 |   ==> 5. Executing build steps
 |   ==>   5.1.  [ 1/2 ] conditional1 conditional2 - Success
 |   ==>   5.2.  [ 2/2 ] true_branch - Success
 |   ==> Nowhere to report. Skipping...
 └ [Success]

7. Finalizing
 |   7.1. Cleaning copied sources
 |      └ [Success]
 |   
 └ [Success]

==> Universum 0.19.17 finished execution
```

**Comment by k-dovgan** [comment]
I still think that descriptions from comments should be added to documentation (e.g. as docstrings, or, preferably, directly to RTD docs).

**Pull request closed without merging**
