### PR TITLE
feat(docs): apply 'collapsible' to pages of documentation

### PR DESCRIPTION
**Pull request by k-dovgan**
Applies #557

### CODE REVIEW

**Comment by k-dovgan** [comment]
Example: https://universum.readthedocs.io/en/apply-collapsible/configuring.html#build-step

**Comment by i-keliukh** [comment]
In my opinion the collapsible block should be applied only if there are more than 4 lines of code.
BTW, now I think we should remove the animation.

**Comment by k-dovgan** [comment]
> BTW, now I think we should remove the animation.

Any arguments why? I think it looks pretty and not annoying.

**Comment by k-dovgan** [comment]
This is a test comment.

**Comment by k-dovgan** [comment]
This is another test comment

**Comment by k-dovgan** [comment]
This is one more test comment

**Review by i-keliukh — APPROVED** [review]

**Pull request merged**
